# Generated by Django 4.1.7 on 2023-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Makaleye Fotoğraf Ekleyin'),
        ),
    ]
