# Generated by Django 4.1.7 on 2023-04-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Makaleye Fotoğraf Ekleyin'),
        ),
    ]
